import "@/styles/globals.scss";
import "moment/locale/ru";
import "react-loading-skeleton/dist/skeleton.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { inter, montserrat } from "utils";
import { SkeletonTheme } from "react-loading-skeleton";
import { ThemeContextProvider } from "@/contexts";
import { Header } from "@/components/layout/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html className={`${inter.variable} ${montserrat.variable}`} lang="ru">
			<body>
				<ThemeContextProvider>
					<SkeletonTheme
						baseColor="var(--color-background-400)"
						borderRadius={5}
						highlightColor="var(--color-background-500)"
					>
						<div className="page">
							<Header />
							{children}
						</div>
					</SkeletonTheme>
				</ThemeContextProvider>
				<Analytics />
			</body>
		</html>
	);
}
